name: diff
on: pull_request
jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}

      - run: git diff --name-only origin/${{ github.head_ref }}