name: environment
on: workflow_dispatch
env:
  NAME: name
  URL: url
jobs:
  env1:
    runs-on: ubuntu-latest
    environment:
      name: "environment 1"
      url: "https://github.com/"
    steps:
      - run: echo hello
  env2:
    runs-on: ubuntu-latest
    environment:
      name: environment-2
      url: "https://github.com/"
    steps:
      - run: echo hello
  env3:
    runs-on: ubuntu-latest
    environment:
      name: environment 3
      url: ${{ env.URL }}
    steps:
      - run: echo hello
  env4:
    runs-on: ubuntu-latest
    environment:
      name: ${{ env.NAME }}
      url: ${{ env.EMPTY }}
    steps:
      - run: echo hello
