name: envs
on: [workflow_dispatch]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      run: |
        echo ${{env.GITHUB_ACTION}}
        echo ${{env.GitHub}}
        echo ${{env.GITHUB_ACTION_PATH}}
        echo ${{env.GITHUB_ACTION_REPOSITORY}}
        echo ${{env.GITHUB_ACTIONS}}
        echo ${{env.GITHUB_ACTOR}}
        echo ${{env.GITHUB_API_URL}}
        echo ${{env.GITHUB_BASE_REF}}
        echo ${{env.GITHUB_ENV}}
        echo ${{env.GITHUB_EVENT_NAME}}
        echo ${{env.GITHUB_EVENT_PATH}}
        echo ${{env.GITHUB_GRAPHQL_URL}}
        echo ${{env.GITHUB_HEAD_REF}}
        echo ${{env.GITHUB_JOB}}
        echo ${{env.GITHUB_PATH}}
        echo ${{env.GITHUB_REF}}
        echo ${{env.GITHUB_REF_NAME}}
        echo ${{env.GITHUB_REF_PROTECTED}}
        echo ${{env.GITHUB_REF_TYPE}}
        echo ${{env.GITHUB_REPOSITORY}}
        echo ${{env.GITHUB_REPOSITORY_OWNER}}
        echo ${{env.GITHUB_RETENTION_DAYS}}
        echo ${{env.GITHUB_RUN_ATTEMPT}}
        echo ${{env.GITHUB_RUN_ID}}
        echo ${{env.GITHUB_RUN_NUMBER}}
        echo ${{env.GITHUB_SERVER_URL}}
        echo ${{env.GITHUB_SHA}}
        echo ${{env.GITHUB_WORKFLOW}}
        echo ${{env.GITHUB_WORKSPACE}}
        echo ${{env.RUNNER_ARCH}}
        echo ${{env.RUNNER_NAME}}
        echo ${{env.RUNNER_OS}}
        echo ${{env.RUNNER_TEMP}}
        echo ${{env.RUNNER_TOOL_CACHE}}
