name: global env
on: push
env:
  SAMPLE: "sample"
jobs:
  job-1:
    runs-on: ubuntu-latest
    outputs:
      output-1: ${{ steps.step-1.outputs.test }}
    steps:
      - id: step-1
        run: echo "::set-output name=test::`date`"
  job-2:
    runs-on: ubuntu-latest
    needs: job-1
    steps:
      - run: echo ${{ needs.job-1.outputs.output-1 }}
