name: global env
on: [workflow_dispatch]
env:
  SAMPLE: "sample"
jobs:
  echo-1:
    runs-on: ubuntu-latest
    steps:
      - name: Test 1
        run: echo ${{ env.SAMPLE }}
  echo-2:
    runs-on: ubuntu-latest
    steps:
      - name: Test 2
        run: echo ${{ env.SAMPLE }}
