name: TypeScript diff

on: workflow_dispatch

jobs:
  typescript-diff:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: "16"

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - run: git rev-parse HEAD

      - run: echo ::set-output name=commit::$(git merge-base main $GITHUB_REF)
        id: ref

      - uses: actions/checkout@v3
        with:
          ref: ${{ steps.ref.outputs.commit }}

      - run: git rev-parse HEAD
