on: workflow_dispatch

jobs:
  Build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: echo semi; echo colon;
        shell: bash
      - run: npm run semicolon
        shell: bash
      - run: yarn run semicolon
        shell: bash
